"""The worked example must stay a worked example.

It exists so the evidence board can be seen before a Parallel credential is
attached. That is only acceptable while it remains impossible to mistake for a
real finding, and while it keeps being generated by the code that serves real
runs rather than drifting into a hand-written picture of the past.
"""

from __future__ import annotations

from urllib.parse import urlparse

from fastapi.testclient import TestClient

from app.api.main import api
from app.example_dossier import worked_example

#: RFC 2606 reserves these. They can never resolve to a real page, so a reader
#: who checks a citation in the example finds a placeholder — the right answer.
RESERVED_SUFFIXES = (".example.org", ".example.com", ".example.net", ".example")


def _all_urls(payload: dict) -> list[str]:
    found: list[str] = []

    def walk(node: object) -> None:
        if isinstance(node, str):
            if node.startswith(("http://", "https://")):
                found.append(node)
        elif isinstance(node, dict):
            for value in node.values():
                walk(value)
        elif isinstance(node, (list, tuple)):
            for value in node:
                walk(value)

    walk(payload)
    return found


def test_every_cited_url_is_an_unresolvable_reserved_domain() -> None:
    """The property that makes publishing a fabricated dossier safe.

    If a real domain ever appears here, the example stops being obviously
    illustrative and starts looking like a finding about a real page.
    """
    for url in _all_urls(worked_example()):
        host = (urlparse(url).hostname or "").lower()
        assert host.endswith(RESERVED_SUFFIXES), f"{url} is not a reserved example domain"


def test_the_example_is_marked_as_one_at_every_level() -> None:
    response = TestClient(api).get("/v1/example/dossier")
    assert response.status_code == 200
    body = response.json()
    assert body["meta"]["example"] is True
    assert body["data"]["example"] is True
    assert "not a real investigation" in body["meta"]["disclaimer"]
    assert "not a real investigation" in body["data"]["disclaimer"]


def test_the_example_needs_no_api_key() -> None:
    """A judge should be able to see the output shape before minting anything."""
    assert TestClient(api).get("/v1/example/dossier").status_code == 200


def test_the_gate_really_ran() -> None:
    """The verdict is computed, not typed.

    Every threshold must be present with a boolean, and the passed/failed lists
    must agree with the thresholds — which is only true if `IdentityGate`
    produced them.
    """
    gate = worked_example()["gate"]
    thresholds = gate["thresholds"]
    assert len(thresholds) == 7
    assert all(isinstance(value, bool) for value in thresholds.values())
    assert set(gate["passed"]) == {n for n, v in thresholds.items() if v}
    assert set(gate["failed"]) == {n for n, v in thresholds.items() if not v}


def test_the_example_demonstrates_the_gate_refusing() -> None:
    """It must never show a probable identity.

    An example that sails through every threshold teaches the wrong thing about
    a product whose headline metric is zero false-confident identifications.
    This one is blocked by an unresolved contradiction and by the human-approval
    threshold no API call can satisfy.
    """
    gate = worked_example()["gate"]
    assert gate["verdict"] == "candidates"
    assert "human_approved" in gate["failed"]
    assert "unresolved_contradictions==0" in gate["failed"]
    assert gate["requires_human"] is True


def test_the_example_shows_a_citation_refused_by_the_live_audit() -> None:
    """The single most important behaviour the board has to make visible."""
    evidence = worked_example()["evidence"]
    refused = [
        source
        for claim in evidence["claims"]
        for source in claim["sources"]
        if source["live_verified"] is False
    ]
    assert refused, "the example must show at least one citation failing the Extract audit"
    for source in refused:
        assert source["counts_toward_gate"] is False

    reasons = {row["reason"] for row in evidence["rejected_citations"]}
    assert "quoted_text_absent_from_live_page" in reasons


def test_the_example_shows_an_unsupported_claim() -> None:
    """A claim with no source is reported, not hidden, so a human can see it."""
    evidence = worked_example()["evidence"]
    unsupported = [c for c in evidence["claims"] if not c["sources"]]
    assert unsupported
    assert all(c["decisive_eligible"] is False for c in unsupported)


def test_the_example_exercises_five_parallel_surfaces() -> None:
    surfaces = worked_example()["parallel_retrieval"]["surfaces_used"]
    assert {
        "parallel_search_v1",
        "parallel_task_v1",
        "parallel_findall_v1beta",
        "parallel_extract_v1",
        "parallel_task_group_v1",
    } <= set(surfaces)
