"""A worked example of a dossier, for showing the output shape before a live run.

The evidence board is the product. Until a Parallel credential is attached, no
visitor can see one, which means the most important screen is invisible exactly
when someone is deciding whether the project is any good.

This builds one. Three rules make it honest:

1. **It is about a fragment that does not exist.** The subject is the invented
   frame illustrated on the landing page — "Tell Mara the lamp still burns" —
   and the candidate is a made-up 1921 title. No real film is described, so no
   real film can be misattributed by it.

2. **Every source is an RFC 2606 reserved domain** (`example.org`, `example.com`).
   These can never resolve to a real page. A reader who checks a citation finds
   a placeholder, which is the correct answer.

3. **It runs through the real code.** The same `build_evidence` and the same
   `IdentityGate` that serve a live investigation produce this result, so the
   verdict and every threshold below are genuinely computed rather than typed
   out. If the schema or the gate changes, this example changes with it or the
   tests fail. It cannot drift into being a picture of something the software
   no longer does.

The response is marked `example: true` at every level, and the UI renders it
behind a sticky banner it cannot scroll away from.
"""

from __future__ import annotations

from dataclasses import asdict
from typing import Any

from app.evidence_builder import build as build_evidence
from app.evidence_schema import CompiledClaim, CompiledEvidence, CompiledSource
from app.gates.identity import IdentityGate
from app.partners.citation_registry import CitationRegistry

DISCLAIMER = (
    "Worked example. This is not a real investigation: the fragment is invented, "
    "the candidate film does not exist, and every source is an RFC 2606 reserved "
    "domain that can never resolve. It is generated by the same evidence builder "
    "and the same deterministic gate that serve a live run, so the shape and the "
    "thresholds are real even though the evidence is not."
)

_TRADE_QUOTE = (
    "A curious melodrama of the lamplighter's daughter, in which the line "
    "\"Tell Mara the lamp still burns\" is repeated to some effect in the final reel."
)
_CATALOGUE_QUOTE = (
    "Lamplighter's Daughter, The (1921). Producer: Ardwick Photoplays. "
    "Five reels. Held: one incomplete 35mm nitrate print."
)
_CENSUS_QUOTE = "Ardwick Photoplays production file, reel inventory, item 44."
_CONTRA_QUOTE = (
    "The same closing line appears verbatim in the 1924 reissue of an unrelated "
    "Ardwick subject, so the phrase alone does not fix the title."
)
_STOCK_QUOTE = (
    "Edge markings of this form were applied to stock manufactured between 1919 and 1923."
)


def _registry() -> CitationRegistry:
    """Pre-load the registry as though Parallel had really returned these results.

    The citation registry is what stops a claim citing a page Parallel never
    produced. Populating it here is what lets the example exercise the genuine
    verification path instead of bypassing it.
    """
    registry = CitationRegistry()
    registry.record_search(
        {
            "provider": "parallel_search_v1",
            "search_id": "search_example_0000",
            "results": [
                {
                    "url": "https://trade-papers.example.org/1921/moving-picture-weekly-vol12",
                    "title": "Moving Picture Weekly, vol. 12 (example)",
                    "excerpts": [_TRADE_QUOTE],
                },
                {
                    "url": "https://catalogue.example.com/records/lamplighters-daughter-1921",
                    "title": "Example National Film Catalogue record (example)",
                    "excerpts": [_CATALOGUE_QUOTE],
                },
                {
                    "url": "https://stock-marks.example.org/edge-codes/1919-1923",
                    "title": "Film stock edge-code reference (example)",
                    "excerpts": [_STOCK_QUOTE],
                },
                {
                    "url": "https://reissues.example.org/ardwick/1924-notes",
                    "title": "Reissue notes, Ardwick subjects (example)",
                    "excerpts": [_CONTRA_QUOTE],
                },
                {
                    "url": "https://archive.example.org/holdings/ardwick-44",
                    "title": "Example Regional Film Archive holdings (example)",
                    "excerpts": [_CENSUS_QUOTE],
                },
            ],
        }
    )
    registry.record_findall(
        {
            "provider": "parallel_findall_v1beta",
            "findall_id": "findall_example_0000",
            "institutions": [
                {
                    "name": "Example Regional Film Archive",
                    "url": "https://archive.example.org/holdings/ardwick-44",
                    "match_status": "matched",
                }
            ],
        }
    )
    # One of the five cited pages fails the live Extract audit. That failure is
    # the reason it is here: the example has to show what a refused citation
    # looks like, because that behaviour is the reason to trust the rest.
    registry.record_live_audit(
        "https://trade-papers.example.org/1921/moving-picture-weekly-vol12", True
    )
    registry.record_live_audit(
        "https://catalogue.example.com/records/lamplighters-daughter-1921", True
    )
    registry.record_live_audit("https://stock-marks.example.org/edge-codes/1919-1923", False)
    registry.record_live_audit("https://archive.example.org/holdings/ardwick-44", True)
    registry.record_live_audit("https://reissues.example.org/ardwick/1924-notes", True)
    registry.calls.extend(
        [
            {"provider": "parallel_task_v1", "retrieval_id": "trun_example_0000", "result_count": 3},
            {"provider": "parallel_extract_v1", "retrieval_id": "extract_example_0000", "result_count": 5},
        ]
    )
    return registry


def _compiled() -> CompiledEvidence:
    candidate = "lamplighters_daughter_1921"
    return CompiledEvidence(
        candidates=[
            {
                "candidate_id": candidate,
                "title": "The Lamplighter's Daughter",
                "year": "1921",
                "score": 0.72,
                "rationale": "A rare closing line and a catalogue record agree on title and year.",
            },
            {
                # Named as a work, not described as one. "Unidentified Ardwick
                # reissue" was the label here until app/works.py started type-
                # checking candidates and correctly threw it out: a description
                # of a film cannot be a rival hypothesis to a film, and the gate
                # was then left with a single unopposed candidate. The example
                # has to model the analysis it is demonstrating.
                "candidate_id": "ardwick_lamp_1924",
                "title": "The Ardwick Lamp",
                "year": "1924",
                "score": 0.31,
                "rationale": "The same line recurs in a later reissue, which the evidence cannot yet rule out.",
            },
        ],
        claims=[
            CompiledClaim(
                claim_text=(
                    "A 1921 trade notice quotes the closing line visible in the fragment, "
                    "“Tell Mara the lamp still burns”."
                ),
                subject=candidate,
                stance="supports",
                clue_family="intertitle_text",
                confidence_basis="The phrase is quoted verbatim in a dated contemporary notice.",
                sources=[
                    CompiledSource(
                        url="https://trade-papers.example.org/1921/moving-picture-weekly-vol12",
                        excerpt=_TRADE_QUOTE,
                    )
                ],
            ),
            CompiledClaim(
                claim_text=(
                    "A catalogue record names Ardwick Photoplays as producer and 1921 as the "
                    "release year, and describes one incomplete nitrate print."
                ),
                subject=candidate,
                stance="supports",
                clue_family="studio_or_producer",
                confidence_basis="An institutional catalogue record, independent of the trade notice.",
                sources=[
                    CompiledSource(
                        url="https://catalogue.example.com/records/lamplighters-daughter-1921",
                        excerpt=_CATALOGUE_QUOTE,
                    )
                ],
            ),
            CompiledClaim(
                claim_text=(
                    "One archive catalogue lists a surviving reel from the Ardwick production file."
                ),
                subject=candidate,
                stance="supports",
                clue_family="archive_holding",
                confidence_basis="Returned by the named-catalogue census; the institution's own record.",
                sources=[
                    CompiledSource(
                        url="https://archive.example.org/holdings/ardwick-44",
                        excerpt=_CENSUS_QUOTE,
                    )
                ],
            ),
            CompiledClaim(
                claim_text=(
                    "The visible edge markings are consistent with stock manufactured between "
                    "1919 and 1923."
                ),
                subject=candidate,
                stance="supports",
                clue_family="visual_or_material",
                confidence_basis=(
                    "Cited to an edge-code reference, but the quotation was not found on the live "
                    "page at audit time, so this claim cannot be decisive."
                ),
                sources=[
                    CompiledSource(
                        url="https://stock-marks.example.org/edge-codes/1919-1923",
                        excerpt=_STOCK_QUOTE,
                    )
                ],
            ),
            CompiledClaim(
                claim_text=(
                    "The same closing line appears verbatim in a 1924 reissue of an unrelated "
                    "Ardwick subject, so the phrase alone does not fix the title."
                ),
                subject=candidate,
                stance="contradicts",
                clue_family="intertitle_text",
                confidence_basis="Found by the Skeptic while searching for competing attributions.",
                sources=[
                    CompiledSource(
                        url="https://reissues.example.org/ardwick/1924-notes",
                        excerpt=_CONTRA_QUOTE,
                    )
                ],
            ),
            CompiledClaim(
                claim_text=(
                    "A performer credited on the catalogue record cannot be confirmed in the "
                    "fragment; no source was found either way."
                ),
                subject=candidate,
                stance="neutral",
                clue_family="performer",
                confidence_basis="Reported without a source so a human can see what is unsupported.",
                sources=[],
            ),
        ],
        temporal_compatibility=True,
        entity_compatibility=True,
        unresolved_questions=[
            "Does the 1924 reissue reuse the intertitle card itself, or only the line?",
            "Is the archive's incomplete print the same five-reel version the catalogue describes?",
            "No non-English trade coverage was searched; a foreign release title may exist.",
        ],
    )


def worked_example() -> dict[str, Any]:
    """Build the example through the real evidence builder and the real gate."""
    registry = _registry()
    compiled = _compiled()
    evidence = build_evidence(compiled, registry)
    gate = IdentityGate().evaluate(
        claims=evidence.claims,
        # False for the same reason it is false on every live run: approving an
        # identity is an archivist action, not an API call.
        context=evidence.gate_context(human_approved=False),
    )
    return {
        "example": True,
        "disclaimer": DISCLAIMER,
        "status": "completed",
        "session_id": "lsa_worked_example",
        "sample_id": None,
        "origin": "worked-example",
        "model": "gemini-2.5-flash",
        "agent_runtime": "google-adk",
        "depth": "deep",
        "latency_ms": 87_400,
        "outputs": {
            "visual_examiner": {
                "intertitles": ["Tell Mara the lamp still burns"],
                "proper_nouns": ["Mara"],
                "logos": ["a small diamond producer's mark, lower right"],
                "material": ["edge markings visible on two frames"],
                "note": "Identity deliberately not proposed at this stage.",
            },
            "phrase_hunter": "Searched the closing line as a literal quoted phrase across four diverse probes; two dated sources returned it.",
            "holdings_researcher": "One producer traced; one archive catalogue lists a surviving reel. No additional holding was found across these named catalogues as of this search date: Example Regional Film Archive.",
            "skeptic": "The closing line recurs in a 1924 reissue of a different Ardwick subject. That contradiction is unresolved.",
            "evidence_compiler": "Six claims compiled; one carries no source and is reported as unsupported.",
        },
        "evidence": evidence.as_dict(),
        "parallel_retrieval": {
            "session_id": "lsa_worked_example",
            "calls": registry.calls,
            "sources_returned": len(registry.sources),
            "independent_domains": sorted(registry.domains),
            "surfaces_used": [
                "parallel_search_v1",
                "parallel_task_v1",
                "parallel_findall_v1beta",
                "parallel_extract_v1",
                "parallel_task_group_v1",
            ],
        },
        "citation_audit": {
            "provider": "parallel_extract_v1",
            "status": "completed",
            "extract_id": "extract_example_0000",
            "pages_requested": 5,
            "pages_returned": 5,
            "errors": [],
            "audited": [
                {
                    "url": "https://trade-papers.example.org/1921/moving-picture-weekly-vol12",
                    "excerpt_present_on_live_page": True,
                    "page_title": "Moving Picture Weekly, vol. 12 (example)",
                    "publish_date": "1921-06-11",
                    "note": "quoted text found in the live page",
                },
                {
                    "url": "https://catalogue.example.com/records/lamplighters-daughter-1921",
                    "excerpt_present_on_live_page": True,
                    "page_title": "Example National Film Catalogue record (example)",
                    "publish_date": None,
                    "note": "quoted text found in the live page",
                },
                {
                    "url": "https://stock-marks.example.org/edge-codes/1919-1923",
                    "excerpt_present_on_live_page": False,
                    "page_title": "Film stock edge-code reference (example)",
                    "publish_date": None,
                    "note": "quoted text not found in the live page at audit time",
                },
                {
                    "url": "https://archive.example.org/holdings/ardwick-44",
                    "excerpt_present_on_live_page": True,
                    "page_title": "Example Regional Film Archive holdings (example)",
                    "publish_date": None,
                    "note": "quoted text found in the live page",
                },
                {
                    "url": "https://reissues.example.org/ardwick/1924-notes",
                    "excerpt_present_on_live_page": True,
                    "page_title": "Reissue notes, Ardwick subjects (example)",
                    "publish_date": None,
                    "note": "quoted text found in the live page",
                },
            ],
        },
        "falsification": {
            "provider": "parallel_task_group_v1",
            "status": "completed",
            "task_group_id": "tgrp_example_0000",
            "candidates_attacked": 2,
            "verdicts": [
                {
                    "run_id": "trun_example_0001",
                    "candidate_id": "lamplighters_daughter_1921",
                    "status": "completed",
                    "content": {
                        "disproved": False,
                        "contradictions": [
                            "The closing line is reused in a 1924 Ardwick reissue."
                        ],
                        "checked_but_consistent": [
                            "Release year is compatible with the visible stock period.",
                            "Producer's mark matches the catalogue record's producer.",
                        ],
                        "unresolved": [
                            "Whether the reissue reuses the card itself could not be established."
                        ],
                    },
                    "basis": [],
                },
                {
                    "run_id": "trun_example_0002",
                    "candidate_id": "ardwick_lamp_1924",
                    "status": "completed",
                    "content": {
                        "disproved": False,
                        "contradictions": [],
                        "checked_but_consistent": [
                            "No source was found that rules the reissue out."
                        ],
                        "unresolved": ["Reissue reel inventory is not digitised."],
                    },
                    "basis": [],
                },
            ],
        },
        "language_findings": [
            {
                "rule": "last_copy",
                "matched": "last surviving copy",
                "where": "holdings_researcher.draft",
                "context": (
                    "an early draft of the holdings summary described the archive's reel as the "
                    "last surviving copy of the production"
                ),
                "permitted_instead": (
                    "No additional holding was found across these named catalogues as of this "
                    "search date."
                ),
            }
        ],
        "cold_case": {
            "eligible": True,
            "watchable_strings": ["Tell Mara the lamp still burns"],
            "how": "POST /v1/watch to leave a standing Parallel Monitor on these strings.",
        },
        "transcript": [],
        "gate": {**asdict(gate), "passed": list(gate.passed), "failed": list(gate.failed)},
        "requires_human": True,
    }
